config/routes.rb
Rails.application.routes.draw do
  
   get 'friendships/create'
   get 'friendships/update'
   get  'friendships/destroy'

	root 'home#index'
 
  get '/mymovies', to:'movie_relations#mymovies'
  get '/toprated', to:'home#toprated'
  get '/nowshowing', to:'home#nowshowing'
  get '/upcoming', to:'home#upcoming'
  get '/findfriends',    to:'users#findfriends'
  get '/search', to: 'home#search'
  get 'genre',to: 'home#genre'
  get '/friendrequest', to: 'users#confirm'
  get '/myfriends',to: 'users#myfriends'
    get '/feed',to: 'users#feed'



  devise_for :users
  resources :users, :only => [:show]
  resources :home
  resources :movie_relations
  resources :friendships, only: [:create, :update, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/friendship.rb
class Friendship < ApplicationRecord
	 belongs_to :user
    belongs_to :friend, class_name: "User"



  

  
end

app/models/movie_relation.rb
class MovieRelation < ApplicationRecord
	belongs_to :user
	validates :user_id, presence: true
  validates :movie_id, presence: true


   
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :picture, PictureUploader
  validate  :picture_size
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :movie_relations,dependent: :destroy    

  has_many :friendships,dependent: :destroy
    has_many :received_friendships, class_name: "Friendship", foreign_key: "friend_id",dependent: :destroy

    has_many :active_friends, -> { where(friendships: { accepted: true}) }, through: :friendships, source: :friend
    has_many :received_friends, -> { where(friendships: { accepted: true}) }, through: :received_friendships, source: :user
    has_many :pending_friends, -> { where(friendships: { accepted: false}) }, through: :friendships, source: :friend
    has_many :requested_friendships, -> { where(friendships: { accepted: false}) }, through: :received_friendships, source: :user

# to call all your friends

    def friends
      active_friends | received_friends
    end

# to call your pending sent or received

    def pending
        pending_friends | requested_friendships
    end

  def my(other_movie) 
    MovieRelation.where("user_id=? AND movie_id=?",id,other_movie.id)
  end   

  def finding(movie)
   	 MovieRelation.where("user_id=? AND movie_id=?",id,movie)
   end	 

  def get_user_movies
    MovieRelation.where("user_id=?",id)
  end

  def movies1
   friend_ids="SELECT friend_id FROM friendships
                 WHERE user_id = :id AND accepted='t' "
   MovieRelation.where("user_id IN (#{friend_ids})",id: id)
  end  

  def movies2
    user_ids="SELECT user_id FROM friendships
               WHERE accepted='t' AND friend_id=:id"
    MovieRelation.where("user_id IN (#{user_ids})" ,id: id)
  end

 

  def self.search(search)
    where("name LIKE ?","%#{search}%")
  end

 private

def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

  


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  	  before_action :authenticate_user!

  	  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email,:date_of_birth, :password,:password_confirmation,:picture) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email,:date_of_birth, :password,:password_confirmation,:current_password) }
        end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
      @friendship = current_user.friendships.build(friend_id: params[:friend_id])
      respond_to do |format|
      if @friendship.save
        flash[:notice] = "Friend requested."
        format.html {redirect_to :back}
        format.js 
      
    
      else
        flash[:notice]="Friend request not send"
    
        format.html {redirect_to :back}
      end
      end
      
    end

    def update
      @friendship = Friendship.where(:user_id=>params[:id]).where(:friend_id=>current_user.id)
      @id=@friendship[0].user_id
      respond_to do |format| 
      if @friendship.update(accepted: true)
        format.html {redirect_to root_url, notice: "Successfully confirmed friend!"}
        format.js
      else
        format.html {redirect_to root_url, notice: "Sorry! Could not confirm friend!"}
      end
      end
    end

    def destroy
      @friendship = Friendship.where(:user_id=>params[:id]).where(:friend_id=>current_user.id)
      @friendship.destroy(@friendship.ids)
      flash[:notice] = "Removed friendship."
      redirect_to :back
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	Tmdb::Api.key("d1a15870f12c8fa7845e143bc760eac3")

	def index
		@details=Tmdb::Movie.popular
    end	

    def show
		@movie= Tmdb::Movie.detail(params[:id])
        @items=current_user.my(@movie)
	end	

	def search
		if params[:search]
        @details=Tmdb::Search.movie(params[:search])
        @users=User.search(params[:search])
      
	end	
end


  def findfriends
   end

    def genre
    	@details=Tmdb::Genre.movies(params[:genre_id])
   end

   def toprated
   	@details=Tmdb::Movie.top_rated
   end

   def nowshowing
   	@details=Tmdb::Movie.now_playing
   end
   
   def upcoming
   	@details=Tmdb::Movie.upcoming
   end	

  def feed
      @friends=current_user.friends
 end
   	
end

app/controllers/movie_relations_controller.rb
class MovieRelationsController < ApplicationController
	attr_accessor :movie_id

	def create
		movie=params[:movie_id]
		movie_title=params[:movie_title]
		@mrel=MovieRelation.new(user_id: current_user.id,movie_id: movie,movie_title: movie_title)
		@mrel_id=@mrel.movie_id
	    respond_to do |format|

		  if @mrel.save
		  	format.html {redirect_to root_path}
		  	format.js
		  end

		 end
		 
		  			
		  
		
	
	
	end
	def mymovies 
       @movies=current_user.get_user_movies
	end	

	def destroy
		@movie=params[:id]
		@mdrel=MovieRelation.where(:user_id=>current_user.id).where(:movie_id=>params[:id])
		@md=MovieRelation.find(@mdrel.ids)
        @mdrel.destroy(@mdrel.ids)
        respond_to do |format|
		 format.html {redirect_to root_path}
		 format.js
		end
		
	end
	
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
	def show
		@user=User.find(params[:id])
		@con1=Friendship.where(:user_id=>current_user.id).where(:friend_id=>params[:id])
		@con2=Friendship.where(:friend_id=>current_user.id).where(:user_id=>params[:id])
    
	end
	def confirm
	end	

    def myfriends
    	@friends=current_user.friends
    end
 
   def feed
      @movies1=current_user.movies1
      @movies2=current_user.movies2
 end

   def findfriends
   	if params[:search]
   		@users=User.search(params[:search])
    end
  end
   	
    

    

   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movie_relations_helper.rb
module MovieRelationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/create.js.erb
$('#choices').html("<%= j render('home/choice')%>");

app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/friendships/ls.html.erb
<h1>
Hello
</h1>

app/views/friendships/update.html.erb
<h1>Friendships#update</h1>
<p>Find me in app/views/friendships/update.html.erb</p>

app/views/friendships/update.js.erb
$("#confirm_<%=@id%>").fadeOut();

app/views/home/_choice.html.erb
<% if @con1==[] && @con2==[] %>
 <%= button_to "Add Friend", friendships_path(friend_id: @user), method: :post,class: "btn btn-primary",remote: true %>
 

   <% else %> 
   <div id="choice2">
   <p>Friends!</p>
   </div>

 <% end %>

app/views/home/_partial.html.erb
<% @details.results.each do |movie| %>
<% @url= "https://image.tmdb.org/t/p/w185/#{movie.poster_path}" %>
   <tbody>
     <tr>
        <div>
         <td> <%= image_tag @url %></td>
         <td> <%= link_to movie.title ,home_path(movie.id)%>
           </td>
           <td>    
              <%= movie.overview %>
         </td>
          
        <td>  <%= movie.release_date %></td>
         
       </div>
     </tr>
   </tbody>
     <%end%>

app/views/home/findfriends.html.erb
<h1>hey</h1>

app/views/home/genre.html.erb
<div class=container>
<br>
<br>
<table class="table table-bordered table-striped table-hover">
 
  <%= render 'home/partial' %>

</table>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
<h1>Welcome to the Movie Mela</h1>
</div>

<div class=container>
<h1>Trending Now!</h1>
<table class="table table-bordered table-striped table-hover">
 
  <%= render 'home/partial' %>

</table>
</div>

app/views/home/nowshowing.html.erb
<div class=container>
<br>
<br>
<table class="table table-bordered table-striped table-hover">
 
  <%= render 'home/partial' %>

</table>
</div>

app/views/home/search.html.erb
<div class=container>
<br>
<br>
<h2>Movies</h2>
<% if @details==[] %>
<h5>no results match your search</h5>
<% else %>
<table class="table table-bordered table-striped table-hover">
 <%= render 'home/partial' %>

</table>
<% end %>

<h2>People</h2>
<% if @users==[] %>
<h5>no results match your search</h5>
<% else %>
<table class="table table-bordered table-striped table-hover">

	<% @users.each do |u| %>
	<tbody>
	<tr>

	  <td><%= u.name %></td>
	  <td><%= link_to u.email ,u%></td>
	  </tr>
	  </tbody>
	  <%end%>
</table>
<% end %>
</div>

app/views/home/show.html.erb
<div id="dd">
<div class="content">
	<div class="poster">
		<%= image_tag "https://image.tmdb.org/t/p/w185/#{@movie.poster_path}" %>
	</div>
	<div class="main">
		<h1><%= @movie.title %></h1>
		<p><%= @movie.overview %></p>

<div id="watch-unwatch" >
 <% if Date.parse(@movie.release_date) < Date.today %>

  <% if @items==[] %>
           
    <%= form_for(current_user.movie_relations.build,:remote => true )do |f|%>
 
  <div><%= hidden_field_tag :movie_id, @movie.id %></div>
    <div><%= hidden_field_tag :movie_title, @movie.title %></div>

  <%= f.submit "Watched", class: "btn btn-primary"%>
  <% end %>
  <% else %>
   
   
   <%= button_to "Unwatch",movie_relation_url(@movie.id),method: :delete, class: "btn btn-danger",remote: true %> 
  
  <%end %>
  <% else %>
    <h6>Not yet released!</h6>
  <% end %>
  </div>
  </div>
	
	<div class="details">
		<h6>Budget:$<%= @movie.budget %></h6>
		<h6>Release Date:<%= @movie.release_date %></h6>
		<h6>Runtime:<%= @movie.runtime %></h6>
	</div>
</div>
</div>

app/views/home/text.html.erb
uechec
fe
feff
ff
eff

app/views/home/toprated.html.erb
<div class=container>
<br>
<br>
<table class="table table-bordered table-striped table-hover">
 
  <%= render 'home/partial' %>

</table>
</div>

app/views/home/upcoming.html.erb
<div class=container>
<br>
<br>
<table class="table table-bordered table-striped table-hover">
 
  <%= render 'home/partial' %>

</table>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a>The movie go app by anuj and tanuj</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://www.bollywoodhungama.com/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div id="topnav">
<nav class="navbar navbar-fixed-top navbar-inverse">

    <div class="navbar-header">
     <%= image_tag("showtime.jpg",height: 50,width: 69)%>

      <a class="navbar-brand" ><%= link_to 'MOVIE' ,root_path,id: "logo" %></a>
  
    </div>
    <% if user_signed_in? %>
    <ul class="nav navbar-nav navbar-right">
     <li><%= link_to 'My Movies','/mymovies' %></li>
          <li><%= link_to 'Top Rated','/toprated' %></li>
          <li><%= link_to 'Now Showing','/nowshowing' %></li>
          <li><%= link_to 'Upcoming','/upcoming' %></li>
  

        <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Friends <b class="caret"></b>
          </a>
          <ul class="dropdown-menu" >
      <li><%= link_to 'My friends','/myfriends' %></li>
     <li><%= link_to 'Requests','/friendrequest' %></li>
     <li><%= link_to 'Feed','/feed '%></li>

    </ul>



    <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu" >
    <li><%= link_to 'Profile',current_user %></li>
  <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
  <li class="divider"></li>
  <li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
  </ul>
  </ul>
  <% else %>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
      <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li> 
    </ul>
    <%end%>
  
</nav>
</div>

<% if user_signed_in? %>
      <div class="row" >
        <aside class="col-md-6 col-md-offset-3">
          <%= form_tag('/search', :method => "get", id: "search-form") do %>
              <%= text_field_tag :search, params[:search] ,placeholder: "Search Movies/Friends" %>
             <button  class="btn btn-primary">
             Search
             </button>
        <% end %>
       </aside>
     </div>


    <% end %>

<% if user_signed_in? %>

  <h5 id="detail">
    Logged in as <strong><%= current_user.email %></strong>
</h5>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Junetwo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
<%= render 'layouts/header' %>
    <%= yield %>
 <%= render 'layouts/footer' %>   
   

  </body>
</html>

app/views/movie_relations/_unwatch.html.erb
<%= button_to "Unwatch",movie_relation_url(@mrel_id),method: :delete, class: "btn btn-danger",remote: true %> 
  

app/views/movie_relations/_watch.html.erb
    <%= form_for(current_user.movie_relations.build,:remote => true )do |f|%>
 
  <div><%= hidden_field_tag :movie_id, @md[0].movie_id %></div>
    <div><%= hidden_field_tag :movie_title, @md[0].movie_title %></div>

  <%= f.submit "Watched", class: "btn btn-primary"%>
  <%end%>

app/views/movie_relations/create.js.erb
$('#watch-unwatch').html("<%= j render('unwatch')%>");

app/views/movie_relations/destroy.js.erb
$('#watch-unwatch').html("<%= j render('watch')%>");

app/views/movie_relations/mymovies.html.erb
<div class="container">
<%if @movies==[] %>
<h2>Watched none</h2>
<%else%>
<h1>Movies you have watched</h1>
<table class="table table-bordered table-striped table-hover">
<% @movies.each do |movie| %>
 
   <tbody>
     <tr>
        <div>
        
         <td> <%= link_to movie.movie_title ,home_path(movie.movie_id)%>
           </td>
           
          
        
       </div>
     </tr>
   </tbody>
     <%end%>
     </table>
     <%end%>
     </div>

app/views/users/confirm.html.erb
<div class="content">
<% if current_user.requested_friendships ==[] %>
    <h2>No Requests</h2>
<%else%>

    <% current_user.requested_friendships.each do |request| %>
 
    
      <div id="confirm_<%=request.id%>">
      

      <%= request.email %>
      
       <div style="float:right;">
      <%= button_to "Accept",  friendship_path(id: request.id), method: "put" ,class: "btn btn-primary ",remote: true%>
      </div>
      <div style="float:right;">
      <%= button_to "Decline", friendship_path(id: request.id), method: :delete , class: "btn btn-danger",remote: true%>
      </div>
       <div style="clear:both;">
    </div>
  </div>
    
    
    
<br>
  <% end %>

  <%end%>
  </div>

app/views/users/feed.html.erb
<h2>Feed</h2>
<div class="content">
<table class="table table-bordered table-striped table-hover">
<tbody>
    
    <% @movies1.each do |item1| %>
    <tr>
	<td><strong><%= item1.user.email %></strong> has watched  
    <%= link_to item1.movie_title,home_path(item1.movie_id) %></td>
   <%end%>
   </tr>
   <% if @movies2!=[] %>
   <tr>
   <td><% @movies2.each do |item2| %>
   <%= item2.user.email %> has watched 
   <%= item2.movie_title %>
   </td>
   <%end%>
   </tr>
   <%end%>
</tbody>
</table>
</div>

app/views/users/myfriends.html.erb
<h2>Friends</h2>
<div class="content">
<table class="table table-bordered table-striped table-hover">
<% @friends.each do |friend| %>
<tbody>
<tr>
	<td><%= link_to friend.email,friend %>
	</td>
	</tr>
	</tbody>
<% end %>
</table>	
</div>

app/views/users/show.html.erb
<div class="content">
<div class="poster">
<%= image_tag @user.picture.url if @user.picture? %>
</div>
<div class="main">
<strong><%= @user.email  %></strong>
</div>
<div class="details">
<% if current_user.id == @user.id %>
<% else %>
<div id="choices">
    <%= render 'home/choice' %>
 </div>
 
 <% end %>
 </div>
 </div>
 </div>
 